-- Seed casting vocabulary. Safe to re-run: ON CONFLICT DO NOTHING.

insert into public.taxonomy_terms (category, label)
values
  -- Race & ethnicity (broad, inclusive; add more via API anytime)
  ('race_ethnicity', 'African American'),
  ('race_ethnicity', 'Afro-Caribbean'),
  ('race_ethnicity', 'Afro-Latino'),
  ('race_ethnicity', 'Black British'),
  ('race_ethnicity', 'Black Canadian'),
  ('race_ethnicity', 'East African heritage'),
  ('race_ethnicity', 'West African heritage'),
  ('race_ethnicity', 'North African heritage'),
  ('race_ethnicity', 'Southern African heritage'),
  ('race_ethnicity', 'African (unspecified region)'),
  ('race_ethnicity', 'Afghan'),
  ('race_ethnicity', 'Arab'),
  ('race_ethnicity', 'Armenian'),
  ('race_ethnicity', 'Bangladeshi'),
  ('race_ethnicity', 'Biracial'),
  ('race_ethnicity', 'Black'),
  ('race_ethnicity', 'Cambodian'),
  ('race_ethnicity', 'Central Asian heritage'),
  ('race_ethnicity', 'Chinese'),
  ('race_ethnicity', 'Cuban'),
  ('race_ethnicity', 'Dominican'),
  ('race_ethnicity', 'Egyptian'),
  ('race_ethnicity', 'Ethiopian'),
  ('race_ethnicity', 'Filipino'),
  ('race_ethnicity', 'French Canadian'),
  ('race_ethnicity', 'German'),
  ('race_ethnicity', 'Ghanaian'),
  ('race_ethnicity', 'Greek'),
  ('race_ethnicity', 'Guatemalan'),
  ('race_ethnicity', 'Haitian'),
  ('race_ethnicity', 'Hmong'),
  ('race_ethnicity', 'Indian (South Asian)'),
  ('race_ethnicity', 'Indigenous (Central/South American)'),
  ('race_ethnicity', 'Indigenous Australian'),
  ('race_ethnicity', 'Inuit'),
  ('race_ethnicity', 'Iranian'),
  ('race_ethnicity', 'Irish'),
  ('race_ethnicity', 'Israeli'),
  ('race_ethnicity', 'Italian'),
  ('race_ethnicity', 'Jamaican'),
  ('race_ethnicity', 'Japanese'),
  ('race_ethnicity', 'Jewish (ethnic/cultural)'),
  ('race_ethnicity', 'Korean'),
  ('race_ethnicity', 'Latin American'),
  ('race_ethnicity', 'Latino'),
  ('race_ethnicity', 'Lebanese'),
  ('race_ethnicity', 'Marshallese'),
  ('race_ethnicity', 'Mexican'),
  ('race_ethnicity', 'Middle Eastern'),
  ('race_ethnicity', 'Multiracial'),
  ('race_ethnicity', 'Native American'),
  ('race_ethnicity', 'Native Hawaiian'),
  ('race_ethnicity', 'Nigerian'),
  ('race_ethnicity', 'Pacific Islander'),
  ('race_ethnicity', 'Pakistani'),
  ('race_ethnicity', 'Palestinian'),
  ('race_ethnicity', 'Persian'),
  ('race_ethnicity', 'Polish'),
  ('race_ethnicity', 'Portuguese'),
  ('race_ethnicity', 'Puerto Rican'),
  ('race_ethnicity', 'Romani'),
  ('race_ethnicity', 'Russian'),
  ('race_ethnicity', 'Salvadoran'),
  ('race_ethnicity', 'Samoan'),
  ('race_ethnicity', 'Scottish'),
  ('race_ethnicity', 'Somali'),
  ('race_ethnicity', 'South Asian'),
  ('race_ethnicity', 'Southeast Asian'),
  ('race_ethnicity', 'Spanish'),
  ('race_ethnicity', 'Sri Lankan'),
  ('race_ethnicity', 'Syrian'),
  ('race_ethnicity', 'Taiwanese'),
  ('race_ethnicity', 'Thai'),
  ('race_ethnicity', 'Tongan'),
  ('race_ethnicity', 'Turkish'),
  ('race_ethnicity', 'Ukrainian'),
  ('race_ethnicity', 'Vietnamese'),
  ('race_ethnicity', 'Welsh'),
  ('race_ethnicity', 'White'),
  ('race_ethnicity', 'White British'),
  ('race_ethnicity', 'White European (general)'),
  ('race_ethnicity', 'Prefer not to specify'),

  -- Age presentation (casting bands)
  ('age_range', 'Appears under 18'),
  ('age_range', 'Appears 18-24'),
  ('age_range', 'Appears mid-20s'),
  ('age_range', 'Appears late 20s'),
  ('age_range', 'Appears 30-39'),
  ('age_range', 'Appears 40-49'),
  ('age_range', 'Appears 50-59'),
  ('age_range', 'Appears 60-69'),
  ('age_range', 'Appears 70+'),
  ('age_range', 'Ageless / stylized'),
  ('age_range', 'Child (casting band)'),
  ('age_range', 'Teen (casting band)'),
  ('age_range', 'Young adult'),
  ('age_range', 'Middle age'),
  ('age_range', 'Senior'),

  -- Height (search-friendly buckets + common imperial markers)
  ('height', 'Under 5''0"'),
  ('height', '5''0" - 5''3"'),
  ('height', '5''4" - 5''7"'),
  ('height', '5''8" - 5''11"'),
  ('height', '6''0" - 6''3"'),
  ('height', '6''4" - 6''7"'),
  ('height', 'Over 6''8"'),
  ('height', 'Petite frame'),
  ('height', 'Average height'),
  ('height', 'Tall'),
  ('height', 'Very tall'),
  ('height', 'Under 155 cm'),
  ('height', '155-165 cm'),
  ('height', '166-175 cm'),
  ('height', '176-185 cm'),
  ('height', 'Over 186 cm'),

  -- Weight / build (casting-oriented)
  ('weight', 'Slender'),
  ('weight', 'Lean athletic'),
  ('weight', 'Athletic / muscular'),
  ('weight', 'Average build'),
  ('weight', 'Stocky'),
  ('weight', 'Broad-shouldered'),
  ('weight', 'Heavyset'),
  ('weight', 'Plus-size'),
  ('weight', 'Body varies by role'),
  ('weight', 'Runner build'),
  ('weight', 'Swimmer build'),

  ('eye_color', 'Brown'),
  ('eye_color', 'Dark brown'),
  ('eye_color', 'Black'),
  ('eye_color', 'Blue'),
  ('eye_color', 'Green'),
  ('eye_color', 'Hazel'),
  ('eye_color', 'Gray'),
  ('eye_color', 'Amber'),
  ('eye_color', 'Heterochromia'),
  ('eye_color', 'Contacts / cosmetic lenses'),

  ('hair_style', 'Straight'),
  ('hair_style', 'Wavy'),
  ('hair_style', 'Curly'),
  ('hair_style', 'Coily'),
  ('hair_style', 'Natural texture'),
  ('hair_style', 'Locs'),
  ('hair_style', 'Twists'),
  ('hair_style', 'Braids'),
  ('hair_style', 'Cornrows'),
  ('hair_style', 'Bantu knots'),
  ('hair_style', 'Buzz cut'),
  ('hair_style', 'Fade'),
  ('hair_style', 'Undercut'),
  ('hair_style', 'Pompadour'),
  ('hair_style', 'Afro'),
  ('hair_style', 'TWA (teeny weeny afro)'),
  ('hair_style', 'Wig / hairpiece'),
  ('hair_style', 'Toupee (visible for character)'),
  ('hair_style', 'Shaved head'),
  ('hair_style', 'Bald (natural)'),
  ('hair_style', 'Thinning hair'),
  ('hair_style', 'Relaxed / chemically straightened'),
  ('hair_style', 'Extensions'),

  ('hair_length', 'Bald / shaved'),
  ('hair_length', 'Buzz / fades'),
  ('hair_length', 'Short (above ears)'),
  ('hair_length', 'Ear length'),
  ('hair_length', 'Chin length'),
  ('hair_length', 'Shoulder length'),
  ('hair_length', 'Mid-back'),
  ('hair_length', 'Long (past mid-back)'),
  ('hair_length', 'Very long'),

  ('hair_color', 'Black'),
  ('hair_color', 'Dark brown'),
  ('hair_color', 'Medium brown'),
  ('hair_color', 'Light brown'),
  ('hair_color', 'Auburn'),
  ('hair_color', 'Red'),
  ('hair_color', 'Strawberry blonde'),
  ('hair_color', 'Blonde'),
  ('hair_color', 'Platinum blonde'),
  ('hair_color', 'Gray'),
  ('hair_color', 'Silver'),
  ('hair_color', 'Salt and pepper'),
  ('hair_color', 'White'),
  ('hair_color', 'Fashion / vivid color'),
  ('hair_color', 'Highlights / balayage'),
  ('hair_color', 'Dyed black'),

  ('facial_hair', 'Clean shaven'),
  ('facial_hair', 'Light stubble'),
  ('facial_hair', 'Heavy stubble'),
  ('facial_hair', 'Mustache only'),
  ('facial_hair', 'Soul patch'),
  ('facial_hair', 'Goatee'),
  ('facial_hair', 'Van Dyke'),
  ('facial_hair', 'Circle beard'),
  ('facial_hair', 'Full beard'),
  ('facial_hair', 'Mutton chops'),
  ('facial_hair', 'Sideburns'),
  ('facial_hair', 'Chin strap'),

  ('beard_style', 'No beard'),
  ('beard_style', 'Designer stubble'),
  ('beard_style', 'Short beard'),
  ('beard_style', 'Medium beard'),
  ('beard_style', 'Long beard'),
  ('beard_style', 'Tapered beard'),
  ('beard_style', 'Boxed beard'),
  ('beard_style', 'Garibaldi'),
  ('beard_style', 'Ducktail'),
  ('beard_style', 'Braided beard'),
  ('beard_style', 'Groomed / corporate'),
  ('beard_style', 'Rugged / unkempt (character)')
on conflict (category, label) do nothing;

-- Optional: link Marcus King sample row to African American + a few physical buckets if present
insert into public.actor_taxonomy (actor_id, term_id)
select a.id, t.id
from public.actors a
join public.taxonomy_terms t
  on t.category = 'race_ethnicity' and t.label = 'African American'
where a.name = 'Marcus King'
on conflict do nothing;

insert into public.actor_taxonomy (actor_id, term_id)
select a.id, t.id
from public.actors a
join public.taxonomy_terms t
  on t.category = 'height' and t.label = '6''0" - 6''3"'
where a.name = 'Marcus King'
on conflict do nothing;

insert into public.actor_taxonomy (actor_id, term_id)
select a.id, t.id
from public.actors a
join public.taxonomy_terms t
  on t.category = 'weight' and t.label = 'Athletic / muscular'
where a.name = 'Marcus King'
on conflict do nothing;
